vim.keymap.set("n", "<leader>ff", "<cmd>Files<cr>")
vim.keymap.set("n", "<leader>fg", "<cmd>GFiles<cr>")
vim.keymap.set("n", "<leader>fb", "<cmd>Buffers<cr>")
vim.keymap.set("n", "<leader>fh", "<cmd>History<cr>")
vim.keymap.set("n", "<leader>fc", "<cmd>Commits<cr>")
vim.keymap.set("n", "<leader>fw", "<cmd>Windows<cr>")
-- fzf = require('fzf-lua')
-- vim.keymap.set("n", "<c-k>f", "<cmd>Files<cr>")
-- vim.keymap.set("n", "<c-k>b", "<cmd>Buffers<cr>")
